import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../api.js';
import { useAuth } from '../context/AuthContext.jsx';
import { AppShell, PageHeader, Card, Avatar, Progress } from '../components/AppShell.jsx';

export default function Profile(){
  const {user,token,logout}=useAuth(); const [tutorId,setTutorId]=useState(null); const [message,setMessage]=useState('');
  const [form,setForm]=useState({headline:'',bio:'',hourlyRate:'',masteryLevel:'',yearsExperience:''}); const [slot,setSlot]=useState({startTime:'',endTime:''});
  useEffect(()=>{if(user?.role==='tutor') api.searchTutors({search:user.full_name}).then(({tutors})=>{const mine=tutors.find(t=>t.user_id===user.id);if(mine){setTutorId(mine.tutor_id);setForm({headline:mine.headline||'',bio:'',hourlyRate:mine.hourly_rate||'',masteryLevel:mine.mastery_level||'',yearsExperience:mine.years_experience||''})}}).catch(()=>{})},[user]);
  if(!user)return <AppShell><div className="page"><PageHeader title="Profil"/><Card><p>Connectez-vous pour accéder à votre profil.</p><Link className="primary-btn" to="/login">Se connecter</Link></Card></div></AppShell>;
  async function save(e){e.preventDefault();if(!tutorId)return;try{await api.updateTutor(tutorId,form,token);setMessage('Profil mis à jour.')}catch(err){setMessage(err.message)}}
  async function addSlot(e){e.preventDefault();if(!tutorId)return;try{await api.addAvailability(tutorId,slot,token);setMessage('Créneau ajouté.');setSlot({startTime:'',endTime:''})}catch(err){setMessage(err.message)}}
  return <AppShell><div className="page"><PageHeader title="Profil utilisateur"/><div className="profile-hero"><Avatar name={user.full_name} size="xl"/><h1>{user.full_name}</h1><p>{user.role==='tutor'?'Tuteur StudyLink':'Apprenant StudyLink'}</p></div><div className="metric-row"><span><b>12</b><small>Sessions</small></span><span><b>8</b><small>Mentors</small></span><span><b>24</b><small>Documents</small></span></div><Card><div className="setting-row"><b>Mes réservations</b><Link to="/bookings">›</Link></div><div className="setting-row"><b>Mes apprentissages</b><Link to="/catalogue">›</Link></div><div className="setting-row"><b>Mes documents</b><Link to="/materials">›</Link></div><div className="setting-row"><b>Développement personnel</b><Link to="/personal-development">›</Link></div><div className="setting-row"><b>Mon projet entrepreneurial</b><Link to="/entrepreneurship/project">›</Link></div></Card>{message&&<div className="info-banner">{message}</div>}{user.role==='tutor'&&<><Card><h2>Informations professionnelles</h2><form onSubmit={save} className="stack"><input value={form.headline} onChange={e=>setForm({...form,headline:e.target.value})} placeholder="Titre affiché"/><textarea rows="4" value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})} placeholder="Votre présentation"/><div className="dual-actions"><input type="number" value={form.hourlyRate} onChange={e=>setForm({...form,hourlyRate:e.target.value})} placeholder="Tarif horaire"/><input type="number" value={form.yearsExperience} onChange={e=>setForm({...form,yearsExperience:e.target.value})} placeholder="Années d’expérience"/></div><button className="primary-btn">Enregistrer</button></form></Card><Card><h2>Ajouter une disponibilité</h2><form onSubmit={addSlot} className="stack"><input type="datetime-local" required value={slot.startTime} onChange={e=>setSlot({...slot,startTime:e.target.value})}/><input type="datetime-local" required value={slot.endTime} onChange={e=>setSlot({...slot,endTime:e.target.value})}/><button className="outline-btn">Ajouter le créneau</button></form></Card></>}<button className="outline-btn full" onClick={logout}>Déconnexion</button></div></AppShell>
}
