import { useEffect, useMemo, useState } from 'react';
import { Link, useParams, useNavigate } from 'react-router-dom';
import { api } from '../api.js';
import { useAuth } from '../context/AuthContext.jsx';
import { AppShell, PageHeader, Card, Chip, Progress, Avatar, Logo } from '../components/AppShell.jsx';

const avatars = [
  'https://i.pravatar.cc/160?img=12','https://i.pravatar.cc/160?img=47','https://i.pravatar.cc/160?img=13','https://i.pravatar.cc/160?img=32','https://i.pravatar.cc/160?img=5'
];
const tutorFallback = [
  {id:1, full_name:'Marc T.', headline:'Python · IA · Machine Learning', avg_rating:4.9, review_count:284, hourly_rate:25, avatar_url:avatars[0]},
  {id:2, full_name:'Sophie L.', headline:'Mathématiques', avg_rating:4.8, review_count:197, hourly_rate:20, avatar_url:avatars[1]},
  {id:3, full_name:'Thomas D.', headline:'Java · Spring Boot', avg_rating:4.7, review_count:210, hourly_rate:30, avatar_url:avatars[2]},
  {id:4, full_name:'Amina K.', headline:'Physique · Mécanique', avg_rating:4.9, review_count:189, hourly_rate:22, avatar_url:avatars[3]},
];
const sessions = [
  ['Python – Avancé','Marc T.','15 mai 2025 · 15:30','Confirmée',avatars[0]],
  ['Mathématiques','Sophie L.','16 mai 2025 · 10:00','Confirmée',avatars[1]],
  ['Java – Spring Boot','Thomas D.','17 mai 2025 · 14:00','À venir',avatars[2]],
  ['Algo & Structures de données','Armin K.','18 mai 2025 · 11:00','À venir',avatars[4]],
];
const courses = [
  {title:'Python pour débutants', mentor:'Marie T.', rating:'4,9', level:'Débutant', progress:65, tone:'python'},
  {title:'Machine Learning', mentor:'Marc T.', rating:'4,8', level:'Intermédiaire', progress:30, tone:'ai'},
  {title:'Algorithmes & Structures', mentor:'Sophie L.', rating:'4,7', level:'Intermédiaire', progress:80, tone:'code'},
];
const categories = ['Informatique','Mathématiques','Physique','Langues','Emploi & Carrière','Développement personnel','Data Science','Business'];

export function HomePage(){
  return <AppShell><div className="page"><PageHeader title="Bonjour, David 👋" subtitle="Prêt à avancer dans votre apprentissage ?" />
    <Card className="next-session"><div><span className="eyebrow">Prochaine session</span><div className="row gap"><Avatar src={avatars[1]} /><div><h3>Python – Programmation avancée</h3><p>Avec Marie T. · Aujourd’hui 14:00 – 16:00</p></div></div></div><Link className="primary-btn" to="/session/1">Rejoindre</Link></Card>
    <div className="quick-grid">{[['Messages','2','/messages'],['Forum','5','/forum'],['Notifications','7','/alerts']].map(([l,n,to])=><Link to={to} className="quick-card" key={l}><b>{l}</b><span>{n}</span></Link>)}</div>
    <div className="section-title"><h2>Mes apprentissages</h2><Link to="/catalogue">Voir tout</Link></div>
    <Card>{courses.map(c=><div className="learning-row" key={c.title}><div className={`course-icon ${c.tone}`}>◈</div><div className="grow"><div className="between"><b>{c.title}</b><strong>{c.progress}%</strong></div><Progress value={c.progress}/></div></div>)}</Card>
    <div className="section-title"><h2>Explorer StudyLink</h2></div><div className="feature-grid">{[['Développement personnel','/personal-development','✦'],['Entrepreneuriat','/entrepreneurship','↗'],['Bootcamps','/bootcamps','⚑'],['Prépa entretien','/career-prep','◎']].map(([l,to,i])=><Link to={to} className="feature-card" key={l}><span>{i}</span><b>{l}</b></Link>)}</div>
  </div></AppShell>
}

export function LoginPage(){
  const {login}=useAuth(); const nav=useNavigate(); const [form,setForm]=useState({email:'',password:''}); const [error,setError]=useState('');
  async function submit(e){e.preventDefault(); try{const r=await api.login(form); login(r.token,r.user); nav('/');}catch(err){setError(err.message)}}
  return <AppShell><div className="auth-page"><Logo/><h1>Bienvenue !</h1><p>Connectez-vous à votre compte</p><form onSubmit={submit}><label>Email ou téléphone<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="exemple@email.com"/></label><label>Mot de passe<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="••••••••"/></label>{error&&<p className="error">{error}</p>}<button className="primary-btn full">Se connecter</button></form><div className="or">ou continuer avec</div><div className="social-row"><button>Google</button><button>Apple</button></div><p>Pas encore de compte ? <Link to="/register">S’inscrire</Link></p></div></AppShell>
}

export function SearchTutorsPage(){
  const [tutors,setTutors]=useState(tutorFallback); const [q,setQ]=useState('');
  useEffect(()=>{api.searchTutors({search:q}).then(r=>setTutors(r.tutors?.length?r.tutors:tutorFallback)).catch(()=>setTutors(tutorFallback))},[q]);
  return <AppShell><div className="page"><PageHeader title="Recherche de tuteurs" back/><div className="search-box">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher un tuteur, une compétence..."/><span>☷</span></div><div className="chip-row"><Chip active>Compétence</Chip><Chip>Matière</Chip><Chip>Disponibilité</Chip><Chip>Tarif</Chip></div><div className="stack">{tutors.map((t,i)=><Link to={`/tutors/${t.id}`} className="tutor-list-card" key={t.id}><Avatar src={t.avatar_url||avatars[i%avatars.length]} size="lg"/><div className="grow"><h3>{t.full_name}</h3><p>{t.headline||t.subjects?.join(' · ')}</p><span>★ {t.avg_rating||'4.9'} ({t.review_count||120})</span></div><b>{t.hourly_rate||25}€/h</b></Link>)}</div><div className="info-banner">✓ Des tuteurs vérifiés et qualifiés</div></div></AppShell>
}

export function TutorProfilePage(){
  const {id}=useParams(); const [t,setT]=useState(tutorFallback[0]);
  useEffect(()=>{api.getTutor(id).then(r=>setT({...tutorFallback[0],...r.tutor})).catch(()=>{})},[id]);
  return <AppShell><div className="page"><PageHeader title="Profil d’un tuteur" back/><div className="profile-hero"><Avatar src={t.avatar_url||avatars[0]} size="xl"/><h1>{t.full_name||'Marc T.'}</h1><p>{t.headline||'Python · IA · Machine Learning'}</p><div className="rating-line">★ {t.avg_rating||4.9} <span>({t.review_count||256} avis)</span><b>{t.hourly_rate||25}€/h</b></div></div><div className="metric-row"><span>🎓 5 ans d’expérience</span><span>🌐 2 langues</span><span>⌖ Paris, France</span></div><div className="tabs"><b>À propos</b><span>Disponibilités</span><span>Avis</span></div><Card><p>Ingénieur en IA et développeur Python passionné, j’aide les étudiants et les professionnels à maîtriser Python, le Machine Learning et l’Intelligence Artificielle.</p><div className="detail-list"><p><b>Spécialités</b><br/>Python, Machine Learning, Deep Learning, Data Science, IA</p><p><b>Niveaux enseignés</b><br/>Débutant · Intermédiaire · Avancé</p><p><b>Langues</b><br/>Français · Anglais</p></div></Card><div className="dual-actions"><Link className="outline-btn" to={`/messages/${id}`}>Contacter</Link><Link className="primary-btn" to={`/reserve/${id}`}>Réserver</Link></div></div></AppShell>
}

export function CalendarPage(){const slots=['09:00 – 10:00','10:30 – 11:30','13:00 – 14:00','15:00 – 16:00','17:00 – 18:00'];return <AppShell><div className="page"><PageHeader title="Calendrier & Disponibilités" back/><Card className="calendar"><h2>Mai 2025</h2><div className="week-head">{['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(d=><span>{d}</span>)}</div><div className="date-grid">{Array.from({length:35},(_,i)=><span className={i===16?'selected-date':''}>{i<3?[28,29,30][i]:i-2}</span>)}</div></Card><h2>Disponibilités du 14 mai</h2><div className="stack">{slots.map(s=><button className={`slot-btn ${s.startsWith('15')?'active':''}`}>{s}</button>)}</div><div className="info-banner">ⓘ Vous pouvez annuler jusqu’à 2 h avant la session.</div></div></AppShell>}

export function ReservePage(){return <AppShell><div className="page"><PageHeader title="Réservation d’une session" back/><Card className="mentor-summary"><Avatar src={avatars[0]} size="lg"/><div><h2>Réserver une session avec Marc T.</h2><p>Python · IA · Machine Learning</p><span>★ 4,9 (256 avis)</span></div></Card><Card><h2>Détails de la session</h2>{[['Matière','Python – Programmation avancée'],['Date','15 mai 2025'],['Heure','15:30 – 16:30'],['Durée','1 heure'],['Tarif','25,00 €']].map(([a,b])=><div className="setting-row"><b>{a}</b><span>{b} ›</span></div>)}</Card><Card><h3>Objectif de la session (optionnel)</h3><textarea placeholder="Ex. : Je souhaite mieux comprendre les décorateurs en Python"/></Card><div className="info-banner">🛡 Paiement sécurisé · Annulation flexible</div><Link className="primary-btn full" to="/bookings">Confirmer la réservation</Link></div></AppShell>}

export function BookingsPage(){const {token,user}=useAuth(); const [list,setList]=useState(sessions); useEffect(()=>{if(token) api.myBookings(token).then(r=>r.bookings?.length&&setList(r.bookings.map((b,i)=>[b.subject_name||'Session',user?.role==='tutor'?b.student_name:b.tutor_name,new Date(b.start_time).toLocaleString('fr-FR'),b.status==='confirmed'?'Confirmée':'À venir',avatars[i%avatars.length]]))).catch(()=>{})},[token]);return <AppShell><div className="page"><PageHeader title="Mes sessions"/><div className="tabs"><b>À venir</b><span>En cours</span><span>Terminées</span><span>Annulées</span></div><div className="stack">{list.map((s,i)=><Link to={`/session/${i+1}`} className="session-row"><Avatar src={s[4]} size="lg"/><div className="grow"><h3>{s[0]}</h3><p>Avec {s[1]}</p><span>{s[2]}</span></div><Chip tone={s[3]==='Confirmée'?'green':'blue'}>{s[3]}</Chip><b>›</b></Link>)}</div></div></AppShell>}

export function SessionDetailPage(){return <AppShell><div className="page"><PageHeader title="Détail d’une session" back/><h1>Python – Programmation avancée</h1><div className="between"><div className="row gap"><Avatar src={avatars[0]}/><span>Avec Marc T.</span></div><Chip tone="green">✓ Confirmée</Chip></div><Card>{[['Date','15 mai 2025'],['Heure','15:30 – 16:30'],['Durée','1 heure'],['Mode','En ligne (Visioconférence)']].map(([a,b])=><div className="setting-row"><b>{a}</b><span>{b}</span></div>)}</Card><Card><h3>Objectif</h3><p>Approfondir les concepts avancés de Python et résoudre des exercices pratiques.</p></Card><Card><h3>Documents</h3>{['Exercice_test.pdf','Notes_cours.pdf'].map(f=><div className="file-row"><span className="file-icon">PDF</span><div className="grow"><b>{f}</b><p>1,2 Mo · PDF</p></div><span>↓</span></div>)}</Card><Link className="primary-btn full" to="/video-session">▣ Rejoindre la session</Link></div></AppShell>}

export function VideoSessionPage(){return <AppShell><div className="page video-page"><PageHeader title="Visioconférence" subtitle="Connexion sécurisée" back/><div className="video-stage"><img src="https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=1200&q=80"/><div className="video-name">● Marc T.<small>Mentor Python</small></div><div className="video-self"><img src="https://i.pravatar.cc/300?img=47"/><b>Sophie L.</b></div><span className="timer">00:24:15</span></div><div className="video-controls">{[['♬','Micro'],['▣','Caméra'],['⇧','Partager'],['□','Chat'],['☎','Quitter']].map(([i,l])=><button className={l==='Quitter'?'danger':''}><span>{i}</span>{l}</button>)}</div></div></AppShell>}

export function MaterialsPage(){const docs=['Python – Bases.pdf','Exercices – Boucles.pdf','Projet – API REST.pdf','Présentation – ML.pptx','Notes de cours.docx'];return <AppShell><div className="page"><PageHeader title="Matériels & Documents" subtitle="Accédez à tous vos supports de cours et ressources d’apprentissage."/><div className="search-box">⌕<input placeholder="Rechercher un document, un cours..."/><span>☷</span></div><div className="chip-row"><Chip active>Tous</Chip><Chip>Cours</Chip><Chip>Sessions</Chip><Chip>Bootcamps</Chip></div><Card>{docs.map((d,i)=><div className="file-row"><span className={`file-icon type-${i>2?'doc':'pdf'}`}>{i>2?'DOC':'PDF'}</span><div className="grow"><b>{d}</b><p>{i%2?'Algorithmes & Structures':'Python pour débutants'}</p><span>Mis à jour le {12-i*2} mai 2025</span></div><b>⋮</b></div>)}</Card></div></AppShell>}

export function ForumPage(){const topics=[['Comment optimiser un algo ?','Python','18 réponses','3'],['Intégrales doubles','Maths','12 réponses','2'],['Aide projet IA','IA & ML','7 réponses',''],['Entretien Tech – questions','Emploi','23 réponses','5'],['Ressources pour progresser en SQL','Autres','9 réponses','1']];return <AppShell><div className="page"><PageHeader title="Forum"/><div className="search-box">⌕<input placeholder="Rechercher dans le forum..."/></div><div className="chip-row"><Chip active>Toutes</Chip><Chip>Python</Chip><Chip>Maths</Chip><Chip>Emploi</Chip><Chip>Autres</Chip></div><Card>{topics.map(([t,c,r,n])=><div className="forum-row"><div className="topic-icon">◈</div><div className="grow"><h3>{t}</h3><p>Je travaille sur un sujet et j’aimerais vos conseils pour progresser...</p><span>{c} · {r} · il y a 15 min</span></div>{n&&<b className="badge">{n}</b>}</div>)}</Card><button className="primary-btn full">＋ Nouvelle discussion</button></div></AppShell>}

export function MessagesPage(){const people=[['Marc T.','Bonjour David, n’oublie pas notre session demain à 14h.','2',avatars[0]],['Sophie L.','Merci pour ton aide ! J’ai mieux compris la régression linéaire.','1',avatars[1]],['Thomas D.','Peux-tu m’envoyer les ressources sur les arbres de décision ?','',avatars[2]],['Amina K.','Parfait, merci ! À demain pour la session de révision.','1',avatars[3]]];return <AppShell><div className="page"><PageHeader title="Messages"/><div className="chip-row"><Chip active>Tous</Chip><Chip>Tuteurs</Chip><Chip>Apprenants</Chip><Chip>● Non lus</Chip></div><Card>{people.map(([n,m,u,a],i)=><Link to={`/messages/${i+1}`} className="message-row"><Avatar src={a} size="lg"/><div className="grow"><h3>{n}</h3><p>{m}</p></div><div><span>{i?'Hier':'10:24'}</span>{u&&<b className="badge blue">{u}</b>}</div></Link>)}</Card></div></AppShell>}

export function ConversationPage(){return <AppShell><div className="page conversation-page"><div className="chat-header"><button onClick={()=>history.back()}>←</button><Avatar src={avatars[0]}/><div className="grow"><h2>Marc T.</h2><p>● En ligne</p></div><span>☎ ⋮</span></div><div className="chat-body"><span className="day-pill">Aujourd’hui</span><div className="bubble incoming">Bonjour David ! 👋<br/>Voici le document avec des exercices avancés en Python comme demandé.<small>10:24</small></div><div className="bubble incoming file-bubble"><b>PDF</b><span>Exercices_avances.pdf<br/><small>1,4 Mo</small></span></div><div className="bubble outgoing">Merci beaucoup 🙏<br/>Je vais regarder ça et je reviens vers toi si besoin !<small>10:27 ✓✓</small></div><div className="bubble incoming">Parfait, à très vite ! 🚀<small>10:28</small></div></div><div className="composer">⌕<input placeholder="Écrire un message..."/><button>➤</button></div></div></AppShell>}

export function AlertsPage(){const a=[['Nouveau message de Marc T.','Bonjour ! J’ai une question sur l’exercice 3.','10:24'],['Sophie L. a répondu à votre discussion.','Merci pour votre question, voici ma réponse...','09:15'],['Rappel : votre session commence dans 30 min.','Python – Programmation avancée avec Marie T.','08:30'],['Nouveau bootcamp disponible !','Data Science pour débutants – Inscrivez-vous dès maintenant.','08:05']];return <AppShell><div className="page"><PageHeader title="Centre d’alertes" subtitle="Restez informé de tout ce qui compte."/><div className="chip-row"><Chip active>Tout</Chip><Chip>Messages</Chip><Chip>Forum</Chip><Chip>Bootcamps</Chip></div><h2>Aujourd’hui</h2><div className="stack">{a.map(x=><Card className="alert-row"><div className="alert-icon">◉</div><div className="grow"><b>{x[0]}</b><p>{x[1]}</p></div><span>{x[2]} ·</span></Card>)}</div></div></AppShell>}

export function CataloguePage(){return <AppShell><div className="page"><PageHeader title="Catalogue des cours" subtitle="Découvrez et développez vos compétences"/><div className="search-box">⌕<input placeholder="Rechercher un cours, un tutoriel..."/></div><div className="chip-row"><Chip>Catégories⌄</Chip><Chip>Niveau⌄</Chip><Chip>Type⌄</Chip><Chip>Langue⌄</Chip></div><div className="section-title"><h2>Catégories principales</h2><Link to="#">Voir tout</Link></div><div className="category-grid">{categories.map((c,i)=><div className={`category-card c${i}`}><span>{['⌘','∑','⚛','◎','▣','✦','◈','↗'][i]}</span><b>{c}</b><small>{45+i*11} cours</small></div>)}</div><div className="section-title"><h2>Cours populaires</h2><Link to="#">Voir tout</Link></div><div className="course-card-grid">{courses.map((c,i)=><Link to={`/courses/${i+1}`} className="course-card"><div className={`course-cover ${c.tone}`}>◈</div><b>{c.title}</b><span>{c.mentor}</span><small>★ {c.rating} · {c.level}</small></Link>)}</div><div className="section-title"><h2>Tutoriels rapides</h2><Link to="#">Voir tout</Link></div><div className="tutorial-strip">{[['Installer Python','8 min'],['Git & GitHub','12 min'],['Docker','15 min']].map(x=><Link to="/tutorials/python" className="mini-tutorial"><b>{x[0]}</b><span>◷ {x[1]} ▶</span></Link>)}</div></div></AppShell>}

export function CourseDetailPage(){return <AppShell><div className="page"><PageHeader title="Détail du cours" back/><div className="course-hero"><div><Chip active>Python</Chip><h1>Python pour débutants</h1><p>Apprenez les bases de Python et créez vos premiers programmes.</p><div className="row gap"><Avatar src={avatars[0]}/><div><b>Marc T.</b><p>★ 4,9 (256 avis)</p></div></div></div><div className="python-glyph">Py</div></div><div className="metric-row"><span><b>Débutant</b><small>Niveau</small></span><span><b>8h 30m</b><small>Durée</small></span><span><b>24 leçons</b><small>Leçons</small></span></div><div className="tabs"><b>À propos</b><span>Programme</span><span>Avis (256)</span><span>Ressources</span></div><Card><h2>À propos du cours</h2><p>Ce cours est conçu pour les débutants souhaitant apprendre Python pas à pas. Vous découvrirez les concepts essentiels du langage avec des exemples concrets et des exercices pratiques.</p><h3>Objectifs pédagogiques</h3>{['Comprendre les bases de Python et son écosystème','Écrire vos premiers programmes avec confiance','Manipuler des données avec des structures clés','Réaliser un projet pratique'].map(x=><p>✓ {x}</p>)}<Link className="primary-btn full" to="/courses/1/modules">▶ Commencer le cours</Link></Card></div></AppShell>}

export function CourseModulesPage(){const m=['Introduction','Variables & Types','Conditions & Boucles','Fonctions','Structures de données','Projet final'];return <AppShell><div className="page"><PageHeader title="Contenu du cours" back/><div className="row gap course-heading"><div className="course-icon python">Py</div><div><p>Python pour débutants</p><h1>Python – Programmation avancée</h1><span>Avec Marie T.</span></div></div><div className="stack">{m.map((x,i)=><Link to={i===0?'/lessons/python-hello':'#'} className="module-row"><span>{i+1}</span><div className="grow"><h3>Module {i+1} – {x}</h3><p>{3+(i%4)} leçons</p></div><b>⌄</b></Link>)}</div><Card className="progress-card"><div className="progress-ring">65%</div><div className="grow"><div className="between"><h3>Votre progression</h3><span>22 / 34 leçons</span></div><Progress value={65}/><p>Continuez comme ça ! Vous êtes sur la bonne voie.</p></div></Card><div className="info-banner">ⓘ Toutes les vidéos sont à regarder directement dans l’application StudyLink.</div></div></AppShell>}

export function LessonPage(){return <AppShell><div className="page"><PageHeader title="StudyLink" back/><p className="breadcrumb">Mes cours › Python – Programmation avancée › Module 1</p><h1>Leçon 3 : Premier programme en Python</h1><p>Module 1 : Bases de Python · 20 min · Débutant</p><div className="youtube-player"><div className="yt-brand">▶ YouTube</div><div className="yt-title">Premier programme<br/><b>en Python</b></div><button>▶</button><div className="yt-controls">▶ ◀︎ ◉ 🔊 3:45 / 8:32 <span>⚙ ◻ ⛶</span></div></div><div className="tabs"><b>Résumé</b><span>Notes</span><span>Ressources</span><span>Exercices</span></div><Card><h3>Dans cette leçon, vous allez :</h3><p>✓ Créer votre premier programme en Python</p><p>✓ Comprendre la fonction print()</p><p>✓ Exécuter un script Python pas à pas</p><div className="info-banner">ⓘ Chaque expert a commencé par un simple “Hello, World !” 🚀</div></Card><div className="dual-actions"><button className="outline-btn">← Leçon précédente</button><Link className="primary-btn" to="/tutorials/python">Leçon suivante →</Link></div></div></AppShell>}

export function TutorialPage(){return <AppShell><div className="page"><PageHeader title="Tutoriel" back/><h1>Tutoriel : Installer Python sur Windows</h1><p>Suivez ces étapes pour installer Python et commencer à coder.</p><div className="tutorial-layout"><aside>{['Télécharger Python','Lancer l’installation','Ajouter Python au PATH','Vérifier l’installation'].map((x,i)=><div className={i===0?'tutorial-step active':'tutorial-step'}><span>{i+1}</span>{x}</div>)}</aside><div><div className="youtube-player compact"><div className="yt-title">Installer Python<br/>sur Windows</div><button>▶</button><div className="yt-controls">▶ 🔊 0:00 / 6:45 <span>⚙ YouTube ⛶</span></div></div><Card><Chip active>Étape 1</Chip><h2>Télécharger Python</h2><p>Avant de commencer, nous allons télécharger la dernière version stable de Python depuis le site officiel.</p><p>1. Rendez-vous sur le site officiel de Python.</p><div className="link-box">https://www.python.org/downloads/</div><p>2. Cliquez sur le bouton “Download Python 3.x.x”.</p><p>3. Le fichier d’installation sera téléchargé sur votre ordinateur.</p></Card></div></div><div className="dual-actions"><button className="outline-btn">← Étape précédente</button><button className="primary-btn">Étape suivante →</button></div></div></AppShell>}

export function BootcampsPage(){const b=[['Bootcamp Python Débutant','En cours','12 – 23 mai 2025','128 étudiants'],['Prépa entretien Tech','À venir','26 mai – 8 juin 2025','96 étudiants'],['Atelier CV & LinkedIn','Terminé','5 – 6 mai 2025','142 étudiants']];return <AppShell><div className="page"><PageHeader title="Bootcamps & formations"/><div className="search-box">⌕<input placeholder="Rechercher un bootcamp, une compétence..."/></div><div className="chip-row"><Chip active>En cours</Chip><Chip>À venir</Chip><Chip>Terminés</Chip></div><div className="info-banner">🎁 Nouveaux bootcamps gratuits disponibles. Activez les alertes.</div><div className="stack">{b.map((x,i)=><Card className="bootcamp-card"><div className="boot-icon">{i===0?'Py':i===1?'⌨':'CV'}</div><div className="grow"><div className="between"><Chip tone={i===0?'green':'blue'}>{x[1]}</Chip><Chip tone="green">Gratuit</Chip></div><h2>{x[0]}</h2><p>{x[2]} · {x[3]}</p><Progress value={[60,0,100][i]}/></div><button className={i===2?'outline-btn':'primary-btn'}>{i===2?'Voir le replay':'Rejoindre'}</button></Card>)}</div></div></AppShell>}

export function CareerPrepPage(){return <AppShell><div className="page"><PageHeader title="Prépa entretien d’embauche" subtitle="Boostez votre confiance, décrochez le job ! 🚀"/><Card className="career-hero"><div><Chip active>Prochaine session</Chip><h1>Simulation d’entretien avec Sarah D.</h1><p>Aujourd’hui, 15:00 – 16:00</p></div><Link className="primary-btn" to="/video-session">Rejoindre la session</Link></Card><div className="section-title"><h2>Actions rapides</h2></div><div className="feature-grid career">{['Simulation d’entretien','Correction de CV','Simulation RH','Questions fréquentes','Feedback personnalisé','Atelier pratique'].map((x,i)=><div className="feature-card"><span>{['▣','▤','◉','?','□','♟'][i]}</span><b>{x}</b><small>Conseils et accompagnement personnalisé</small></div>)}</div><div className="section-title"><h2>Mentor recommandé</h2><Link to="#">Voir tout</Link></div><Card className="mentor-summary"><Avatar src={avatars[1]} size="lg"/><div className="grow"><h3>Sarah D.</h3><p>Experte en recrutement & Soft Skills</p><span>★ 4.9 · +5 ans d’expérience</span></div><button className="primary-btn">Réserver</button></Card></div></AppShell>}

export function PersonalDevelopmentPage(){const cats=['Discipline','Yoga','Méditation','Productivité','Confiance en soi','Habitudes','Bien-être','Intelligence émotionnelle'];return <AppShell><div className="page"><PageHeader title="Développement personnel" subtitle="Disciplines, habitudes, bien-être et équilibre"/><div className="search-box">⌕<input placeholder="Rechercher un cours, une compétence, un sujet..."/></div><div className="chip-row"><Chip>Catégories⌄</Chip><Chip>Niveau⌄</Chip><Chip>Type⌄</Chip><Chip>Langue⌄</Chip></div><div className="category-grid personal">{cats.map((c,i)=><div className={`category-card p${i}`}><span>{['◎','♨','✿','▤','●','⟳','❧','♥'][i]}</span><b>{c}</b><small>{11+i} cours</small></div>)}</div><div className="section-title"><h2>Programmes populaires</h2><Link to="#">Voir tout</Link></div><div className="course-card-grid"><Link to="/personal-development/programs/discipline-30" className="course-card image-card"><div className="photo discipline-photo"></div><b>Discipline 30 jours</b><small>★ 4,8 · Débutant</small></Link><div className="course-card image-card"><div className="photo yoga-photo"></div><b>Yoga du matin</b><small>★ 4,9 · Tous niveaux</small></div><div className="course-card image-card"><div className="photo focus-photo"></div><b>Routine anti-procrastination</b><small>★ 4,7 · Débutant</small></div></div><div className="section-title"><h2>Vidéos & Livres</h2><Link to="/personal-development/books">Voir tout</Link></div><div className="media-strip"><div>▶ Comment renforcer votre discipline</div><Link to="/personal-development/books">▣ Atomic Habits</Link><div>▶ Méditation pour réduire le stress</div><Link to="/personal-development/books">▣ Les 5 AM Club</Link></div></div></AppShell>}

export function PersonalProgramPage(){return <AppShell><div className="page"><PageHeader title="Détail du programme" back/><p className="breadcrumb">Programmes de développement › Discipline 30 jours</p><div className="program-hero"><Chip active>Programme</Chip><h1>Discipline<br/>30 jours</h1><p>Transformez vos habitudes.<br/>Changez votre vie.</p><div className="row gap"><Avatar src={avatars[1]}/><span>Coach Sarah M.</span></div><div>★ 4,8 · Débutant · 30 jours</div></div><div className="tabs"><b>À propos</b><span>Programme</span><span>Avis</span><span>Ressources</span></div><Card><h2>À propos de ce programme</h2><p>Un programme pratique et progressif conçu pour renforcer votre autodiscipline, construire des habitudes solides et atteindre vos objectifs personnels et professionnels.</p><h3>Ce que vous allez accomplir</h3>{['Développer une discipline quotidienne durable','Créer et suivre une routine efficace','Améliorer votre concentration et votre productivité','Vaincre la procrastination et passer à l’action'].map(x=><p>✓ {x}</p>)}<div className="info-banner">▣ Suivi quotidien et défis motivants.</div></Card><button className="primary-btn full">Commencer le programme →</button></div></AppShell>}

export function PersonalBooksPage(){const books=[['Atomic Habits','James Clear','Productivité','45%'],['Pouvoir de la discipline','Brian Tracy','Discipline','28%'],['Yoga pour débutants','Elodie Martin','Yoga','60%'],['Maîtriser son temps','Thibault Meurisse','Productivité','35%'],['Confiance en soi','Sarah Ben Ali','Psychologie','15%']];return <AppShell><div className="page"><PageHeader title="Livres de développement personnel" subtitle="Lisez et progressez à votre rythme."/><div className="search-box">⌕<input placeholder="Rechercher un livre, un auteur, un sujet..."/><span>☷</span></div><div className="chip-row"><Chip active>Tous</Chip><Chip>Discipline</Chip><Chip>Motivation</Chip><Chip>Productivité</Chip><Chip>Yoga</Chip></div><h2>Continuer la lecture</h2><Card className="book-feature"><div className="book-cover atomic">Atomic<br/><b>Habits</b></div><div className="grow"><h2>Atomic Habits</h2><p>James Clear</p><Chip>Productivité</Chip><Progress value={45}/></div><b>PDF ⋮</b></Card><h2>Tous les livres</h2><div className="stack">{books.map((b,i)=><Link to={i===1?'/personal-development/books/discipline':'#'} className="book-row"><div className={`book-cover b${i}`}>{b[0].split(' ').slice(0,2).join('\n')}</div><div className="grow"><h3>{b[0]}</h3><p>{b[1]}</p><Chip>{b[2]}</Chip><small>★ {4.5+i/10} · {b[3]}</small></div><span>⋮</span></Link>)}</div></div></AppShell>}

export function BookReaderPage(){return <AppShell><div className="page"><PageHeader title="Lecture du livre" back/><div className="reader-tools"><span>🔖<small>Signet</small></span><span>✎<small>Surligner</small></span><span>▤<small>Notes</small></span><span>Aᴀ<small>Taille du texte</small></span><span>☾<small>Mode nuit</small></span></div><Card className="reader-card"><div className="book-header"><div className="book-cover discipline-book">POUVOIR DE LA DISCIPLINE</div><div className="grow"><h1>Pouvoir de la discipline</h1><p>Brian Tracy</p><Progress value={42}/><span>42% terminé</span></div></div><div className="chapter-nav"><button>←</button><div><p>Chapitre 3</p><h2>Construire une routine durable</h2></div><button>→</button></div><div className="book-text"><p>La réussite ne vient pas de ce que vous faites de temps en temps, mais de ce que vous faites <mark>chaque jour.</mark></p><p>Une routine bien construite est le fondement de toute transformation personnelle. Elle élimine la dépendance à la motivation et installe la discipline comme un pilier de votre quotidien.</p><p>Commencez petit. Choisissez 2 ou 3 habitudes essentielles. Répétez-les chaque jour, sans exception.</p></div><div className="page-pill">Page 52 sur 124 · 42%</div></Card><div className="quote-card">“ La discipline est le pont entre vos objectifs et vos réalisations. ”</div></div></AppShell>}

export function EntrepreneurshipPage(){const cats=['Idée & Validation','Business Plan','Finance','Marketing','Vente','E-commerce','Leadership','Business en ligne'];return <AppShell><div className="page"><PageHeader title="Entrepreneuriat" subtitle="Créez, lancez et développez votre projet"/><div className="search-box">⌕<input placeholder="Rechercher un cours, une compétence, un sujet..."/></div><div className="chip-row"><Chip>Catégories⌄</Chip><Chip>Niveau⌄</Chip><Chip>Type⌄</Chip><Chip>Format⌄</Chip></div><div className="category-grid entrepreneur">{cats.map((c,i)=><div className={`category-card e${i}`}><span>{['💡','▤','◔','⌁','▣','🛒','♟','◎'][i]}</span><b>{c}</b><small>{10+i} cours</small></div>)}</div><div className="section-title"><h2>Parcours populaires</h2><Link to="#">Voir tout</Link></div><div className="course-card-grid"><div className="path-card"><Chip>Débutant</Chip><h3>Créer son entreprise</h3><p>Les étapes clés pour passer de l’idée au lancement.</p><small>8 modules · 6h 30min</small></div><Link to="/entrepreneurship/business-plan" className="path-card"><Chip tone="green">Intermédiaire</Chip><h3>Business plan complet</h3><p>Réalisez un business plan solide et convaincant.</p><small>10 modules · 7h 45min</small></Link><div className="path-card"><Chip>Débutant</Chip><h3>Trouver ses premiers clients</h3><p>Attirez, convertissez et fidélisez vos premiers clients.</p><small>7 modules · 5h 20min</small></div></div><div className="section-title"><h2>Ressources & Modèles</h2><Link to="/entrepreneurship/toolkit">Voir tout</Link></div><div className="resource-grid"><Link to="/entrepreneurship/toolkit">▤ Modèles<br/><small>24 modèles</small></Link><span>▶ Vidéos<br/><small>36 vidéos</small></span><span>▥ Livres & Guides<br/><small>18 ressources</small></span></div></div></AppShell>}

export function BusinessPlanCoursePage(){return <AppShell><div className="page"><PageHeader title="StudyLink" back/><p className="breadcrumb">Mes cours › Entrepreneuriat › Créer son business plan</p><h1>Créer son business plan</h1><p>Apprenez à structurer une idée et bâtir un business plan solide pour lancer votre projet avec confiance.</p><div className="mentor-meta"><Avatar src={avatars[3]}/><span><b>Nadia K.</b><br/>Mentore en entrepreneuriat</span><span>★ 4,8 · Intermédiaire</span><span>◷ 4h 30 min · 18 leçons</span></div><div className="business-hero"><h1>Construisez<br/>votre projet.<br/>Planifiez votre<br/><b>réussite.</b></h1></div><div className="tabs"><b>À propos</b><span>Programme</span><span>Avis</span><span>Ressources</span></div><Card><h2>Résumé</h2><p>Ce parcours vous accompagne pas à pas pour transformer votre idée en un business plan clair, réaliste et convaincant.</p><h3>Objectifs pédagogiques</h3>{['Réaliser une étude de marché pertinente','Définir une proposition de valeur unique','Élaborer un plan financier solide','Mettre en place une stratégie commerciale efficace'].map(x=><p>◉ <b>{x}</b></p>)}<button className="primary-btn full">▶ Commencer le parcours</button></Card></div></AppShell>}

export function EntrepreneurToolkitPage(){const tools=[['Modèle de business plan','DOCX'],['Prévision financière','XLSX'],['Modèle de budget','XLSX'],['Modèle de facture','DOCX'],['Checklist de lancement','PDF'],['Pitch deck','PPTX']];return <AppShell><div className="page"><PageHeader title="Boîte à outils entrepreneur" subtitle="Des modèles et outils pratiques pour lancer, gérer et développer votre projet avec succès." back/><div className="search-box">⌕<input placeholder="Rechercher un modèle ou un outil..."/><span>☷</span></div><div className="chip-row"><Chip active>Tous</Chip><Chip>Modèles</Chip><Chip>Finances</Chip><Chip>Pitch</Chip><Chip>Documents</Chip></div><h2>Modèles et ressources populaires</h2><div className="tools-grid">{tools.map((x,i)=><Card className="tool-card"><div className={`tool-icon t${i}`}>▤</div><div><h3>{x[0]}</h3><p>Modèle professionnel prêt à l’emploi pour votre projet.</p><Chip>{x[1]}</Chip></div><button>↓</button></Card>)}</div><div className="info-banner">ⓘ Conseil StudyLink : personnalisez ces modèles selon vos besoins.</div></div></AppShell>}

export function EntrepreneurProjectPage(){return <AppShell><div className="page"><PageHeader title="Mon projet entrepreneurial" subtitle="Gérez l’avancement de votre projet et atteignez vos objectifs." back/><div className="project-hero"><div className="project-logo">FRESH<br/>BOX</div><div className="grow"><h1>FreshBox Delivery</h1><Chip tone="green">● En cours</Chip><p>Projet créé le 12 avr. 2024</p></div><div className="progress-ring big">65%<small>Avancement</small></div><div className="project-metrics"><span>Lancement prévu<b>15 oct. 2024</b></span><span>Budget utilisé<b>6 450 € / 10 000 €</b></span><span>Prochaine étape<b>Lancement bêta</b></span></div></div><div className="dashboard-grid"><Card><div className="between"><h2>Tâches</h2><Link to="#">Voir tout</Link></div>{['Étude de marché','Création du logo','Rédaction du business plan','Recherche des premiers clients'].map((x,i)=><p>{i<2?'✓':'○'} {x} <span>{i<2?'Terminée':i===2?'En cours':'À faire'}</span></p>)}<Progress value={50}/></Card><Card><h2>Budget</h2><h1>6 450 €</h1><p>sur 10 000 €</p><div className="progress-ring">64%</div></Card><Card><h2>Objectifs</h2>{[['Valider le concept',100],['Développer le MVP',75],['Atteindre 100 clients',30]].map(x=><div><div className="between"><span>{x[0]}</span><b>{x[1]}%</b></div><Progress value={x[1]}/></div>)}</Card><Card><h2>Documents</h2>{['Business Plan v1.2.pdf','Étude de marché.docx','Prévisionnel financier.xlsx'].map(x=><p>▤ {x} ⋮</p>)}</Card></div><div className="info-banner">ⓘ Conseil du jour : pensez à tester votre MVP auprès d’un petit groupe avant le lancement ! 🚀</div></div></AppShell>}
