import { useEffect,useMemo,useState } from 'react'; import { api } from '../../api.js'; import { useAuth } from '../../context/AuthContext.jsx'; import { AdminHeader,Status } from './AdminLayout.jsx';
const cfg={
 tutorials:{title:'Tutoriels',subtitle:'Créez des guides courts et pratiques',resource:'tutorials',key:'tutorials',fields:[['title','Titre'],['description','Description','textarea'],['cover_url','Image de couverture (URL)'],['level','Niveau','select','beginner|intermediate|advanced'],['language','Langue'],['estimated_minutes','Durée (minutes)','number'],['status','Statut','select','draft|review|published|archived']]},
 books:{title:'Livres',subtitle:'Ajoutez des livres autorisés, PDF, ePub, audio ou liens externes',resource:'books',key:'books',fields:[['title','Titre'],['author_name','Auteur'],['description','Description','textarea'],['cover_url','Couverture (URL)'],['file_url','Fichier ou lien (URL)'],['audio_url','Audio (URL)'],['file_type','Format','select','pdf|epub|audio|external'],['rights_status','Droits','select','licensed|public_domain|owned|external_link'],['page_count','Nombre de pages','number'],['status','Statut','select','draft|published|archived']]},
 bootcamps:{title:'Bootcamps',subtitle:'Planifiez et publiez des formations gratuites',resource:'bootcamps',key:'bootcamps',fields:[['title','Titre'],['description','Description','textarea'],['cover_url','Image (URL)'],['mode','Mode','select','online|in_person|hybrid'],['start_at','Date de début','datetime-local'],['end_at','Date de fin','datetime-local'],['max_participants','Places maximum','number'],['meeting_url','Lien de visioconférence'],['replay_url','Replay (URL)'],['status','Statut','select','project|upcoming|ongoing|completed|cancelled']]},
 personal:{title:'Développement personnel',subtitle:'Créez des programmes de discipline, yoga, méditation et habitudes',resource:'personal-programs',key:'programs',fields:[['title','Titre'],['description','Description','textarea'],['cover_url','Image (URL)'],['duration_days','Durée (jours)','number'],['level','Niveau'],['status','Statut','select','draft|published|archived']]},
 entrepreneurship:{title:'Entrepreneuriat',subtitle:'Gérez la boîte à outils des entrepreneurs',resource:'entrepreneur-tools',key:'tools',fields:[['title','Titre'],['description','Description','textarea'],['category','Catégorie'],['file_type','Type de fichier','select','docx|xlsx|pdf|pptx|link|other'],['file_url','Fichier / lien (URL)'],['cover_url','Image (URL)'],['status','Statut','select','draft|published|archived']]}
};
export default function GenericContentPage({type}){const c=cfg[type],{token}=useAuth();const [items,setItems]=useState([]),[open,setOpen]=useState(false),[form,setForm]=useState({}),[err,setErr]=useState('');const load=()=>api.adminList(c.resource,token).then(x=>setItems(x[c.key]||[])).catch(e=>setErr(e.message));useEffect(load,[type,token]);async function submit(e){e.preventDefault();try{await api.adminCreate(c.resource,form,token);setForm({});setOpen(false);load()}catch(e){setErr(e.message)}}async function del(id){if(!confirm('Supprimer cet élément ?'))return;await api.adminDelete(c.resource,id,token);load()}return <><AdminHeader title={c.title} subtitle={c.subtitle} action={<button className="admin-btn primary" onClick={()=>setOpen(true)}>＋ Ajouter</button>}/>{err&&<div className="admin-error">{err}</div>}<div className="admin-content-grid">{items.map(x=><article className="admin-content-card"><div className="admin-cover" style={x.cover_url?{backgroundImage:`url(${x.cover_url})`}:{}}>{!x.cover_url&&'◆'}</div><div><h3>{x.title}</h3><p>{x.description||x.author_name||x.category||'Aucune description'}</p><Status value={x.status}/></div><button onClick={()=>del(x.id)}>Supprimer</button></article>)}</div>{!items.length&&<div className="admin-empty">Aucun contenu pour le moment. Cliquez sur « Ajouter ».</div>}{open&&<div className="admin-modal-bg"><form className="admin-modal" onSubmit={submit}><div className="admin-modal-head"><h2>Ajouter · {c.title}</h2><button type="button" onClick={()=>setOpen(false)}>×</button></div>{c.fields.map(([k,l,t='text',opts])=><label>{l}{t==='textarea'?<textarea rows="4" value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/>:t==='select'?<select value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}><option value="">Choisir...</option>{opts.split('|').map(o=><option value={o}>{o}</option>)}</select>:<input type={t} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/>}</label>)}<div className="admin-actions"><button className="admin-btn primary">Enregistrer</button><button type="button" className="admin-btn" onClick={()=>setOpen(false)}>Annuler</button></div></form></div>}</>}
